## Ejercicios

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Datasets/football_stats.csv', index_col='player_id')
df

,player_name,year,games,goals,npg,shots,assists,yellow_cards,red_cards,position,team_name,time
player_id,,,,,,,,,,,,
8865,Ollie Watkins,2020,9,6,5,22,1,0,0,F,Aston Villa,810
675,Jack Grealish,2020,9,5,5,26,5,2,0,F M,Aston Villa,810
592,Ross Barkley,2020,6,2,2,17,1,0,0,M,Aston Villa,454
1024,Tyrone Mings,2020,9,2,2,7,1,2,0,D,Aston Villa,810
7726,Ezri Konsa Ngoyo,2020,9,2,2,7,0,0,0,D,Aston Villa,810
...,...,...,...,...,...,...,...,...,...,...,...,...
4267,Florian Hartherz,2014,10,0,0,1,2,1,1,D S,Paderborn,775
4268,Christian Strohdiek,2014,22,0,0,6,0,2,0,D S,Paderborn,1608
4311,Idir Ouali,2014,6,0,0,4,0,1,0,M S,Paderborn,296
4334,Mirnes Pepic,2014,2,0,0,0,0,0,0,S,Paderborn,20
4363,Thomas Bertels,2014,1,0,0,0,0,0,0,S,Paderborn,3

#### Usa df.describe() y cuéntanos todos los insights que te dio y qué podría significar cada uno.

In [3]:
description = df.describe() 
print(description)

               year         games         goals           npg         shots  \
count  18633.000000  18633.000000  18633.000000  18633.000000  18633.000000
mean    2016.937691     17.072291      1.624054      1.478399     15.323888
std        1.976606     11.375527      3.252418      2.891849     20.934645
min     2014.000000      1.000000      0.000000      0.000000      0.000000
25%     2015.000000      7.000000      0.000000      0.000000      1.000000
50%     2017.000000     16.000000      0.000000      0.000000      8.000000
75%     2019.000000     27.000000      2.000000      2.000000     21.000000
max     2020.000000     38.000000     48.000000     38.000000    227.000000

            assists  yellow_cards     red_cards          time
count  18633.000000  18633.000000  18633.000000  18633.000000
mean       1.138088      2.453979      0.127569   1207.483282
std        1.936238      2.685745      0.370656    975.753086
min        0.000000      0.000000      0.000000      1.000000
25%        0.000000      0.000000      0.000000    326.000000
50%        0.000000      2.000000      0.000000    976.000000
75%        2.000000      4.000000      0.000000   2004.000000
max       20.000000     17.000000      5.000000   3420.000000

#### Encuentra la cantidad de goles totales hechos por cada posición.

In [4]:
goals_by_position = df.groupby(['position'])['goals'].sum()
goals_by_position

position
D          1238
D F           0
D F M        62
D F M S     637
D F S        25
D M         360
D M S      1213
D S        1494
F          1022
F M         982
F M S      9718
F S        8118
GK            1
GK S          1
M           764
M S        4536
S            90
Name: goals, dtype: int64

#### Cuál es el jugador que más tiempo ha jugado y cuál es la media de tiempo de todos los jugadores?  
Esta pregunta tiene truco porque hay muchos jugadores suplentes que no juegan casi nunca y van a sesgar los datos, cómo podrías solucionar esto?

In [30]:
max_time_index = df['time'].idxmax()
max_time_played = df.loc[max_time_index, 'player_name']

players_mean = str(df['time'].mean())

print('el jugador que más tiempo ha jugado es: ' + max_time_played)
print('Media del tiempo jugado de todos los jugadores: ' + players_mean)

741
player_id
741    el jugador que más tiempo ha jugado es: Jordan...
741    el jugador que más tiempo ha jugado es: Jordan...
741    el jugador que más tiempo ha jugado es: Jordan...
741    el jugador que más tiempo ha jugado es: Jordan...
741    el jugador que más tiempo ha jugado es: Jordan...
741    el jugador que más tiempo ha jugado es: Jordan...
Name: player_name, dtype: object
Media del tiempo jugado de todos los jugadores: 1207.4832823485215

#### Qué posición es la que más tiempo juega? Y la que menos?

In [6]:
time_played_position = df.groupby('position')['time'].sum()
position_max_time_played = str(time_played_position.idxmax())


position_min_time_played = str(time_played_position.idxmin())


print(time_played_position)
print('\nLa posición que mas tiempo juega es: ' + position_max_time_played)
print('La posición que menos tiempo juega es: ' + position_min_time_played)

position
D          2657978
D F            885
D F M        42512
D F M S     386385
D F S        20255
D M         623395
D M S      2133789
D S        3775194
F           170426
F M         264275
F M S      3415956
F S        1807824
GK         1878624
GK S        169820
M           793567
M S        4296344
S            61807
Name: time, dtype: int64

La posición que mas tiempo juega es: M S
La posición que menos tiempo juega es: D F

#### Qué porcentaje de goles son hechos por penales? La columna npg significa: goles hechos SIN penales.

In [7]:
total = df['goals'].sum()
npg = df['npg'].sum()
pg = total - npg

persentage = str((pg * 100) / total)

print('Un ' + persentage + '% de goles son por penales.')

Un 8.968639502990648% de goles son por penales.

#### Qué porcentaje de goles son hechos con asistencias?

In [8]:
total_goals = df['goals'].sum()
assists = df['assists'].sum()

persentage = str((assists * 100) / total_goals)


print('Un ' + persentage + '% de goles son por asistencias.')

Un 70.07699679455405% de goles son por asistencias.

#### Cuál fue el equipo que más goles hizo cada año? Salió campeón ese año?

In [9]:

team_goals = df.groupby(['year', 'team_name'])['goals'].sum()
team_goals = team_goals.reset_index()

max_goals = team_goals.groupby('year')['goals'].idxmax()

team_max_goals = team_goals.loc[max_goals]
team_max_goals = team_max_goals.sort_values('year', ascending=False)

for year, team_name, goals in team_max_goals[['year', 'team_name', 'goals']].values:
    print(f"El equipo que más goles hizo en {year} fue {team_name} con {goals} goles.")

El equipo que más goles hizo en 2020 fue Bayern Munich con 34 goles.
El equipo que más goles hizo en 2019 fue Manchester City con 100 goles.
El equipo que más goles hizo en 2018 fue Paris Saint Germain con 103 goles.
El equipo que más goles hizo en 2017 fue Manchester City con 103 goles.
El equipo que más goles hizo en 2016 fue Barcelona con 114 goles.
El equipo que más goles hizo en 2015 fue Barcelona con 109 goles.
El equipo que más goles hizo en 2014 fue Real Madrid con 116 goles.

#### Cuántos jugadores jugaron todos los años del dataset? Qué porcentaje del total representan?

In [28]:
years_played = df.groupby('player_name')['year'].nunique()

every_year = years_played[years_played == df['year'].nunique()]

#years_played
#every_year

total_every_year = len(every_year)

total = len(years_played)


persentage = (total_every_year * 100) / total


print(f'{total_every_year} jugadores jugaron todos los años.')
print(f'Los jugadores que jugaron todos los años representasn el {persentage}%.')

540 jugadores jugaron todos los años.
Los jugadores que jugaron todos los años representasn el 8.750607681088965%.

In [11]:
df

,player_name,year,games,goals,npg,shots,assists,yellow_cards,red_cards,position,team_name,time
player_id,,,,,,,,,,,,
8865,Ollie Watkins,2020,9,6,5,22,1,0,0,F,Aston Villa,810
675,Jack Grealish,2020,9,5,5,26,5,2,0,F M,Aston Villa,810
592,Ross Barkley,2020,6,2,2,17,1,0,0,M,Aston Villa,454
1024,Tyrone Mings,2020,9,2,2,7,1,2,0,D,Aston Villa,810
7726,Ezri Konsa Ngoyo,2020,9,2,2,7,0,0,0,D,Aston Villa,810
...,...,...,...,...,...,...,...,...,...,...,...,...
4267,Florian Hartherz,2014,10,0,0,1,2,1,1,D S,Paderborn,775
4268,Christian Strohdiek,2014,22,0,0,6,0,2,0,D S,Paderborn,1608
4311,Idir Ouali,2014,6,0,0,4,0,1,0,M S,Paderborn,296
4334,Mirnes Pepic,2014,2,0,0,0,0,0,0,S,Paderborn,20
4363,Thomas Bertels,2014,1,0,0,0,0,0,0,S,Paderborn,3

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18633 entries, 8865 to 4363
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   player_name   18633 non-null  object
 1   year          18633 non-null  int64
 2   games         18633 non-null  int64
 3   goals         18633 non-null  int64
 4   npg           18633 non-null  int64
 5   shots         18633 non-null  int64
 6   assists       18633 non-null  int64
 7   yellow_cards  18633 non-null  int64
 8   red_cards     18633 non-null  int64
 9   position      18633 non-null  object
 10  team_name     18633 non-null  object
 11  time          18633 non-null  int64
dtypes: int64(9), object(3)
memory usage: 2.4+ MB